# encoding: utf-8

control "V-52171" do
	title "The system must provide the capability to automatically process audit records for events of interest based upon selectable event criteria."
	desc "Before a security review, information systems and/or applications with an audit reduction capability may remove many audit records known to have little security significance.

This is generally accomplished by removing records generated by specified classes of events, such as records generated by nightly backups.

An audit reduction capability provides support for near real-time audit review and analysis based on policy requirements regarding what must be audited on the system and after-the-fact investigations of security incidents. It is important to recognize audit reduction does not alter original audit records.

Audit reduction and reporting tools do not alter original audit records.

To leverage the complete capability of audit reduction, the application must possess the ability to specify and automatically process certain event criteria that are selectable in nature. In other words, a system administrator (SA) may be performing a manual review of audit data to identify a particular problem. The SA has determined that backup activity and network connections from a particular host comprise the bulk of the events. However, these events are not related to the activity being investigated. The application must be able to automatically process these audit records for audit reduction purposes rather than making the administrator manually process them.

The lack of audit reduction and reporting in a database can require the DBA, or others responsible for reviewing audit logs, to sort through large amounts of data in order to find relevant records. This can cause important audit records to be missed.

Oracle offers the choice of storing audit data internally in database tables, or in external files.  The WHERE clause in the SELECT statement provides the necessary functionality for a table-based audit.  For an audit based on external files (or for a table-based audit trail archived to external files) Oracle Database does not provide tools for retrieving and managing the data once written.  Therefore, an external tool is needed.false"
	impact 0.5
	tag "check": "Review the system (OS, applications external to Oracle, and/or a separate log aggregation and query server) to determine whether it provides the ability to automatically process audit records for events based on selectable event criteria. If the system does not provide these abilities, they may be handled by a separate application.

If the ability to automatically process audit records for events based on selectable event criteria does not exist, this is a finding."
	tag "fix": "Utilize a tool, application or service that provides the ability to automatically process audit records for events based on selectable event criteria."

	# Write Check Logic Here

end