# encoding: utf-8

control "V-52245" do
	title "Oracle must back up user-level information per a defined frequency."
	desc "Information system backup is a critical step in maintaining data assurance and availability. 

User-level information is data generated by information system and/or application users. In order to assure availability of this data in the event of a system failure, DoD organizations are required to ensure user-generated data is backed up at a defined frequency. This includes data stored on file systems, within databases or within any other storage media.

Applications performing backups must be capable of backing up user-level information per the DoD-defined frequency. 

Databases that do not backup information regularly risk the loss of that information in the event of a system failure. Most databases contain functionality to allow regular backups; it is important that this functionality is enabled and configured correctly to prevent data loss.false"
	impact 0.5
	tag "check": "Review DBMS settings and site documentation to determine whether Oracle is configured to back up user-level data according to a defined frequency.

If it is not, this is a finding.

(The V$RMAN_STATUS view displays the finished and on-going RMAN jobs. For on-going jobs, this view displays progress and status.)"
	tag "fix": "Configure the Oracle DBMS to back up user-level data on a defined frequency."

	# Write Check Logic Here

end