# encoding: utf-8

control "V-92677" do
	title "The Apache web server must invalidate session identifiers upon hosted application user logout or other session termination."
	desc "Captured sessions can be reused in 'replay' attacks. This requirement limits the ability of adversaries from capturing and continuing to employ previously valid session IDs.

Session IDs are tokens generated by web applications to uniquely identify an application user's session. Unique session IDs help to reduce predictability of said identifiers. When a user logs out, or when any other session termination event occurs, the web server must terminate the user session to minimize the potential for an attacker to hijack that particular user session.

"
	impact 0.5
	tag "check": "Determine the location of the 'HTTPD_ROOT' directory and the 'httpd.conf' file:

# httpd -V | egrep -i 'httpd_root|server_config_file'
-D HTTPD_ROOT='/etc/httpd'
-D SERVER_CONFIG_FILE='conf/httpd.conf'

Search for the following directive:

'SessionMaxAge'

# cat /<path_to_file>/httpd.conf | grep -i 'SessionMaxAge'

Verify the value of 'SessionMaxAge' is set to '600' or less.

If the 'SessionMaxAge' does not exist or is set to more than '600', this is a finding."
	tag "fix": "Determine the location of the 'HTTPD_ROOT' directory and the 'httpd.conf' file:

# httpd -V | egrep -i 'httpd_root|server_config_file'
-D HTTPD_ROOT='/etc/httpd'
-D SERVER_CONFIG_FILE='conf/httpd.conf'

Add the following line to the 'httpd.conf' file:

SessionMaxAge 600

Restart Apache: apachectl restart"

	# Write Check Logic Here
	describe apache_conf() do
		its('SessionMaxAge') { should cmp <= 600 }
	end

end
